site_name: Celeste Mod 制作教程
repo_url: https://github.com/Saplonily/CelesteModdingTutorial
repo_name: Saplonily/CelesteModdingTutorial
site_description: Celeste Modding Tutorial
site_author: Saplonily
site_url: https://saplonily.top/celeste_modding_tutorial/

plugins:
  - search
#  - git-revision-date-localized:
#      enable_creation_date: true

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/favicon.png
  font: false
  features:
    - content.code.copy
    - content.tabs.link

  palette: 
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

extra_css:
  - css/content.css

markdown_extensions:
  - admonition
  - meta
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tilde 
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      pygments_lang_class: true
      linenums: true

nav:
  - "首页": "index.md"
  - "地图制作":
    - "软件安装, 游戏配置": "mapping/basic_env.md"
    - "Mod 结构": "mapping/mod_structure.md"
    - "Loenn 基础": "mapping/loenn_basic.md"
    - "房间属性，元数据，文本": "mapping/room_meta_text.md"
    - "Graphics Dump": "shared/graphics_dump.md"
    - "常用参考": "mapping/reference.md"
    - "Dialog": "mapping/dialog.md"
  - "皮肤 Mod 制作":
    - "Graphics Dump": "shared/graphics_dump.md"
  - "Code Mod 制作 (Legacy)":
    - 首页: "code_modding/index.md"
    - 推荐入门顺序:
        - 前言: "code_modding/basics/index.md"
        - 基础环境配置: "code_modding/coding_setup/basic_env.md"
        - 阅读代码: "code_modding/coding_setup/code_reading.md"
        - 调试: "code_modding/coding_setup/debug.md"
        - On 钩子: "code_modding/advanced/hooks/on_hook.md"
        - 简单自定义实体: "code_modding/coding_challenges/simple_entity.md"
        - 简单自定义Trigger: "code_modding/coding_challenges/simple_trigger.md"
        - 简单贴图: "code_modding/coding_challenges/simple_texturing.md"
    - 一些准备:
        - 基础环境配置: "code_modding/coding_setup/basic_env.md"
        - 阅读代码: "code_modding/coding_setup/code_reading.md"
        - 调试: "code_modding/coding_setup/debug.md"
    - 基础:
        - 前言: "code_modding/basics/index.md"
        - Monocle: "code_modding/basics/monocle.md"
        - EC 架构: "code_modding/basics/ec_architecture.md"
        - 生命周期: "code_modding/basics/life_cycle.md"
        - EverestModule: "code_modding/basics/everest_module.md"
        - 数据管理: "code_modding/basics/session_settings_savedata.md"
        - 输入获取: "code_modding/basics/input_handling.md"
        - 碰撞检测: "code_modding/basics/collision_detection.md"
    - 进阶:
        - 钩子:
            - 前言: "code_modding/advanced/hooks/index.md"
            - On 钩子: "code_modding/advanced/hooks/on_hook.md"
            - IL: "code_modding/advanced/hooks/il.md"
            - IL 指令速查表: "code_modding/advanced/hooks/il_instructions.md"
            - IL 钩子: "code_modding/advanced/hooks/il_hook.md"
            - 协程钩取: "code_modding/advanced/hooks/coroutine_hooking.md"
        - 私有访问: "code_modding/advanced/private_access.md"
        - 跨 Mod 交互: "code_modding/advanced/cross_mod_interaction.md"
        - 自定义命令: "code_modding/advanced/custom_command.md"
        - 粒子系统: "code_modding/advanced/particle_system.md"
        - 进阶渲染:
            - Renderer: "code_modding/advanced/rendering/renderer.md"
            - SpriteBatch: "code_modding/advanced/rendering/sprite_batch.md"
            - VirtualRenderTarget: "code_modding/advanced/rendering/virtual_render_target.md"
            - Effect: "code_modding/advanced/rendering/effect.md"
    - Loenn:
        - 开始: "code_modding/loenn/begin.md"
        - 目录结构: "code_modding/loenn/folder_structure.md"
        - Entity 结构: "code_modding/loenn/entity_structs.md" 
        - Trigger 结构: "code_modding/loenn/trigger_structs.md"
        - 渲染: "code_modding/loenn/rendering.md"
    - Wiki:
        - 实体:
            - Player: "code_modding/wiki/entity/player.md"
        - 组件:
            - Sprite, Image: "code_modding/wiki/component/sprite_image.md"
            - Tween: "code_modding/wiki/component/tween.md"  
            - Coroutine: "code_modding/wiki/component/coroutine.md"  
            - Alarm: "code_modding/wiki/component/alarm.md"  
            - StaticMover: "code_modding/wiki/component/static_mover.md" 
            - StateMachine: "code_modding/wiki/component/statemachine.md"  
            - Holdable: "code_modding/wiki/component/holdable.md"
            - BloomPoint, VertexLight: "code_modding/wiki/component/bloompoint_vertaxlight.md"
            - SoundSource: "code_modding/wiki/component/sound_source.md"
        - Level: "code_modding/wiki/level.md"
        - EntityData: "code_modding/wiki/entity_data.md"
        - Tracker: "code_modding/wiki/tracker.md"
        - Flag: "code_modding/wiki/flag.md"
        - Tag: "code_modding/wiki/tag.md" 
    - 实战:
        - 测试地图: "code_modding/coding_challenges/test_map.md"
        - 简单自定义实体: "code_modding/coding_challenges/simple_entity.md"
        - 简单自定义Trigger: "code_modding/coding_challenges/simple_trigger.md"
        - 简单贴图: "code_modding/coding_challenges/simple_texturing.md"
        - 简单自定义组件: "code_modding/coding_challenges/simple_component.md"
    - 额外:
        - XML:
          - XML 简单介绍: "code_modding/extra/xml/xml_speedrun.md"
        - Lua:
          - 开始: "code_modding/extra/lua/begin.md"
          - 基本语法: "code_modding/extra/lua/syntax.md"
          - 数据类型: "code_modding/extra/lua/data_type.md"
          - 流程控制: "code_modding/extra/lua/control_flow.md"
          - 运算符: "code_modding/extra/lua/operator.md"
          - 迭代器: "code_modding/extra/lua/iterator.md"
          - 模块: "code_modding/extra/lua/module.md"
          - 标准库: "code_modding/extra/lua/standard_library.md"
        - LuaCutscene:
          - 开始: "code_modding/extra/lua_cutscene/begin.md"
          - 参考: "code_modding/extra/lua_cutscene/reference.md"
          - C# 交互: "code_modding/extra/lua_cutscene/cs_access.md"
          - 例子: "code_modding/extra/lua_cutscene/examples.md"
    - 历史归档:
        - 基础环境配置: "code_modding/arc/basic_env.md"
        - 通过模板创建项目: "code_modding/arc/project_template.md"
        - 偏好: "code_modding/arc/preference.md"
        - 偏好-sdk-styled-proj: "code_modding/arc/sdk-styled-proj.md"
    - 杂项:
        - ChangeLog: "code_modding/misc/change_log.md"
        - ToDoList: "code_modding/misc/to_do_list.md"